name: vepro
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - cuda-toolkit=11.8
  - cuda-nvrtc=11.8
  - cuda-nvrtc-dev=11.8
  - pytorch
  - torchvision==0.16.0
  - torchaudio==2.1.0
  - pytorch-cuda=11.8
  - pip
  - pip:
    - -r requirements.txt
